# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e70edc5295f834a3156197f2476161d58ea1acedc21eef2cfef542e89380601d51ea324d36b0ada85946acfe76c0754cddb52441b29c7b5f6265dc5e5c54d6d7

test:
  secret_key_base: bc6fc36a71a034ad563c19575744d975f41fff3e525f7501cf9f54340cece5eeefdb6c84729be507c1cb2bbf5d43ad8d8694528af4895986a7bb23d8c15fd71f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
